import { Fragment, useMemo, useState } from 'react'
import { AlertTriangle, ArrowLeft, ArrowRight, Bot, Check, ChevronRight, CircleDot, Clock3, Database, Factory, FileCheck2, FileText, Fish, FlaskConical, History, Info, Layers3, Map, MapPin, Navigation, Network, Radar, Send, ShieldCheck, Sparkles, Upload, Users, Waves, X } from 'lucide-react'
import { anchor, observationLabels, reports } from './data/reports'
import { buildDemoCluster, demoClusterConfidence } from './services/clusteringService'
import { assessRisk } from './services/riskService'
import { reportingIntegration } from './services/integrationService'
import type { Observation } from './types'
import { formatTime } from './utils/format'

type Screen='home'|'report'|'analysis'|'cluster'|'detail'|'structured'|'tracking'|'how'
const steps:Screen[]=['home','report','analysis','cluster','detail','structured','tracking']
const cluster=buildDemoCluster(reports); const risk=assessRisk(cluster)

const Logo=()=> <div className="brand"><span className="logo"><Waves size={18}/><Radar size={14}/></span><span><b>Eco-Alert</b><small>AI CONCIERGE</small></span></div>
const Badge=({children,tone='green'}:{children:React.ReactNode,tone?:string})=><span className={`badge ${tone}`}>{children}</span>
const SafetyNote=({compact=false}:{compact?:boolean})=><div className={`safety-note ${compact?'compact':''}`}><ShieldCheck size={20}/><div><b>AI assesses urgency, not chemical identity.</b>{!compact&&<span>Chemical identity: <strong>Unknown</strong> — requires field/lab verification.</span>}</div></div>

function Shell({screen,setScreen,children}:{screen:Screen,setScreen:(s:Screen)=>void,children:React.ReactNode}){
  const i=steps.indexOf(screen)
  return <div className="app-shell"><header><Logo/><div className="header-actions"><Badge tone="blue"><CircleDot size={9}/> DEMO MODE</Badge><button className="text-btn" onClick={()=>setScreen('how')}><Network size={16}/> How AI works</button></div></header>{i>0&&i<steps.length&&<div className="progress"><span style={{width:`${(i/(steps.length-1))*100}%`}}/></div>}<main>{children}</main><footer><span>Prototype data · Prachin Buri scenario</span><button onClick={()=>setScreen('how')}>Responsible AI & architecture</button></footer></div>
}

function Home({go}:{go:(s:Screen)=>void}){return <div className="page home-page"><section className="hero"><div><Badge tone="green"><Radar size={11}/> LIVE ENVIRONMENTAL INTELLIGENCE</Badge><h1>See the incident<br/>behind the reports.</h1><p>AI connects scattered citizen signals, local context, and risk factors so officers can see <em>where to investigate first.</em></p><div className="hero-actions"><button className="primary big" onClick={()=>go('report')}><AlertTriangle/> แจ้งเหตุผิดปกติ <span>Report an incident</span><ArrowRight/></button><button className="secondary" onClick={()=>go('how')}><Sparkles/> How AI works</button></div></div><div className="signal-visual" aria-label="8 reports combine into one incident"><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="signal-core"><span>8</span><small>REPORTS</small></div>{[0,1,2,3,4,5,6,7].map(n=><i key={n} style={{'--n':n} as React.CSSProperties}/>)}</div></section><section className="nearby-card"><div className="nearby-image"><img src="/assets/canal-evidence.png"/><Badge tone="red">HIGH PRIORITY</Badge></div><div className="nearby-copy"><div className="eyebrow"><Navigation size={14}/> DETECTED 1.2 KM NEARBY</div><h2>Potential pollution incident</h2><p>Multiple citizen reports may point to one larger event near the Prachin Buri canal.</p><div className="incident-stats"><span><b>PB-024</b><small>INCIDENT</small></span><span><b>8</b><small>REPORTS</small></span><span><b>12 min</b><small>LATEST</small></span></div><button className="link" onClick={()=>go('detail')}>View incident intelligence <ArrowRight size={16}/></button></div></section><div className="trust-row"><span><ShieldCheck/> Human verification required</span><span><FlaskConical/> No chemical diagnosis</span><span><Layers3/> Built to augment existing systems</span></div></div>}

function Report({go}:{go:(s:Screen)=>void}){const [selected,setSelected]=useState<Observation[]>(anchor.observations); const toggle=(o:Observation)=>setSelected(s=>s.includes(o)?s.filter(x=>x!==o):[...s,o]); return <div className="page narrow"><div className="page-title"><button className="icon-btn" onClick={()=>go('home')}><ArrowLeft/></button><div><span>NEW CITIZEN REPORT</span><h1>What did you observe?</h1></div></div><div className="report-grid"><section className="upload-card"><img src="/assets/canal-evidence.png"/><div className="photo-label"><Check/> Demo photo added</div><button><Upload/> Replace photo</button></section><section className="form-card"><div className="capture-row"><div><MapPin/><span><b>13.9298, 101.5741</b><small>GPS · ± 8 m</small></span></div><div><Clock3/><span><b>11:36</b><small>2 Oct 2026</small></span></div></div><label>Description <small>ภาษาไทยหรือ English</small></label><textarea defaultValue={anchor.description}/><label>Quick observations <small>Select all that apply</small></label><div className="chips">{Object.entries(observationLabels).map(([o,l])=><button key={o} className={selected.includes(o as Observation)?'selected':''} onClick={()=>toggle(o as Observation)}>{selected.includes(o as Observation)&&<Check/>}{l}</button>)}<button>อื่น ๆ</button></div><div className="privacy"><Info/> Location and evidence are used only for this incident prototype.</div><button className="primary full" onClick={()=>go('analysis')}><Sparkles/> Analyze report <ArrowRight/></button></section></div></div>}

function Analysis({go}:{go:(s:Screen)=>void}){const stages=['Understanding citizen observations','Checking nearby reports','Retrieving location context','Evaluating incident patterns']; const [done,setDone]=useState(false); useState(()=>{setTimeout(()=>setDone(true),1600)}); return <div className="page analysis-page"><div className="analysis-head"><Badge tone="blue"><Sparkles size={11}/> AI TRIAGE COMPLETE</Badge><h1>High-priority pattern detected</h1><p>Your report was evaluated against nearby signals and verified contextual datasets.</p></div><div className="analysis-grid"><section className="score-card"><div className="score-ring"><span>{risk.score}</span><small>/ 100</small></div><Badge tone="red">HIGH PRIORITY</Badge><p>Investigate promptly</p><div className="mini-metric"><b>91%</b><span>cluster confidence</span></div></section><section className="reason-card"><div className="card-title"><span><Radar/> Why this score is high</span><Badge tone="amber">EXPLAINABLE</Badge></div><div className="factor-list">{risk.factors.map((f,i)=><div className="factor" key={f.label}><span className="factor-icon">{i===0?<Users/>:i===1?<Map/>:i===2?<Waves/>:i===3?<Factory/>:i===4?<Fish/>:<History/>}</span><div><b>{f.detail}</b><small>{f.source}</small></div><strong>+{f.points}</strong></div>)}</div></section></div><SafetyNote/><div className="discovery"><div className="discovery-icons"><span className="your-report"><MapPin/>YOU</span><i/><div className="found"><Users/>+7</div></div><div><Badge tone="blue"><Network size={11}/> CLUSTER DISCOVERED</Badge><h2>Your report matches 7 nearby reports</h2><p>They may represent one potential incident—not eight isolated tickets.</p></div><button className="primary" disabled={!done} onClick={()=>go('cluster')}>{done?'Explore incident cluster':'Connecting reports…'} <ArrowRight/></button></div></div>}

function Cluster({go}:{go:(s:Screen)=>void}){return <div className="page cluster-page"><div className="page-title"><button className="icon-btn" onClick={()=>go('analysis')}><ArrowLeft/></button><div><span>INCIDENT CLUSTERING</span><h1>8 reports. One potential incident.</h1></div><Badge tone="amber">91% CONFIDENCE</Badge></div><section className="map-panel"><div className="map-bg"><div className="river"/><div className="road a"/><div className="road b"/><div className="zone industrial"><Factory/> INDUSTRIAL ZONE</div><div className="zone flood"><Waves/> FLOOD-AFFECTED</div><div className="cluster-area"/><div className="cluster-center"><span>8</span><small>PB-024</small></div>{cluster.map((r,i)=><button key={r.id} className="map-pin" style={{left:`${35+(i%4)*7+(i%2)*2}%`,top:`${29+Math.floor(i/4)*23+(i%3)*3}%`}}><MapPin/><span>{r.id}</span></button>)}<button className="map-pin unrelated one"><MapPin/><span>R-201</span></button><button className="map-pin unrelated two"><MapPin/><span>R-202</span></button><div className="legend"><span><i className="dot green"/> Clustered reports</span><span><i className="dot gray"/> Unrelated reports</span><span><i className="dot blue"/> Context zones</span></div></div><aside className="cluster-panel"><div className="merge-hero"><div><span>8</span><small>CITIZEN<br/>REPORTS</small></div><ArrowRight/><div><span>1</span><small>POTENTIAL<br/>INCIDENT</small></div></div><p className="prototype-note">Prototype similarity formula · not scientifically validated</p>{[['Spatial similarity','within 500 m','40%'],['Temporal similarity','6 within 2 hours','30%'],['Semantic similarity','odor · film · dead fish','30%'],['Environmental context','industry + flood zone','context']].map((x,i)=><div className="similarity" key={x[0]}><div className={`sim-icon s${i}`}><CircleDot/></div><div><b>{x[0]}</b><span>{x[1]}</span></div><strong>{x[2]}</strong></div>)}<div className="confidence"><span>Cluster confidence</span><b>91%</b><div><i/></div></div><button className="primary full" onClick={()=>go('detail')}>View incident intelligence <ArrowRight/></button></aside></section></div>}

function Detail({go}:{go:(s:Screen)=>void}){return <div className="page"><div className="page-title"><button className="icon-btn" onClick={()=>go('cluster')}><ArrowLeft/></button><div><span>INCIDENT INTELLIGENCE</span><h1>Incident #PB-024</h1></div><Badge tone="red">HIGH PRIORITY · 87</Badge></div><div className="summary-strip">{[['8','Citizen reports'],['09:42','First report'],['11:36','Latest report'],['91%','Cluster confidence']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><div className="detail-grid"><section><div className="evidence-card"><img src="/assets/canal-evidence.png"/><div><Badge tone="blue">LATEST EVIDENCE</Badge><h2>Prachin Buri canal area</h2><p>13.9298, 101.5741 · Citizen-uploaded image</p><div className="tags"><span>rainbow/oily film</span><span>strong odor</span><span>dead fish</span></div></div></div><div className="observations"><h3>Citizen signal timeline</h3>{cluster.slice(0,5).map(r=><div key={r.id}><time>{formatTime(r.timestamp)}</time><span><b>{r.description}</b><small>{r.id} · {r.observations.map(o=>observationLabels[o]).join(' · ')}</small></span></div>)}</div></section><aside><h3>Context that changes priority</h3>{[[Factory,'Nearby industrial area','420 m','Mock factory registry'],[Waves,'Flood context','Affected zone','Mock DDPM flood layer'],[Users,'Citizen signals','6 / 8','Report strong odor'],[Fish,'Biological signal','3 reports','Mention dead fish'],[History,'Historical context','2 previous','Incidents nearby']].map(([Icon,title,value,sub]:any)=><div className="context-card" key={title}><Icon/><div><span>{title}</span><b>{value}</b><small>{sub}</small></div></div>)}<SafetyNote compact/><button className="primary full" onClick={()=>go('structured')}><FileText/> Generate officer-ready report <ArrowRight/></button></aside></div></div>}

function Structured({go}:{go:(s:Screen)=>void}){return <div className="page narrow-report"><div className="page-title"><button className="icon-btn" onClick={()=>go('detail')}><ArrowLeft/></button><div><span>AI-STRUCTURED OUTPUT</span><h1>Ready for officer review</h1></div><Badge tone="green"><Check/> COMPLETE</Badge></div><div className="document"><div className="doc-head"><Logo/><div><span>INCIDENT INTELLIGENCE REPORT</span><b>#PB-024</b></div></div><div className="doc-alert"><AlertTriangle/><div><b>HIGH PRIORITY · 87 / 100</b><span>Requires field verification</span></div><div><b>91%</b><span>Cluster confidence</span></div></div><div className="doc-grid"><div><label>LOCATION</label><b>Prachin Buri canal area</b><span>13.9298, 101.5741</span></div><div><label>TIME RANGE</label><b>02 Oct 2026 · 09:42–11:36</b><span>Latest report 12 min ago</span></div><div><label>REPORTS / EVIDENCE</label><b>8 citizen reports · 4 photos</b><span>within approximately 500 m</span></div><div><label>CONTEXTUAL RISKS</label><b>Industrial proximity · flood zone</b><span>2 historical incidents nearby</span></div></div><section><label>STRUCTURED OBSERVATIONS</label><div className="tags big"><span>Rainbow / oily film · 3 reports</span><span>Strong odor · 6 reports</span><span>Dead fish · 3 reports</span><span>Discolored water · 2 reports</span></div></section><section><label>AI REASONING SUMMARY</label><p>Eight independent citizen reports form a strong spatial and temporal cluster. Repeated observations of strong odor, surface film, and dead fish—combined with flood-zone context and proximity to a registered industrial area—raise the urgency for prompt field investigation.</p></section><div className="doc-warning"><FlaskConical/><div><b>Chemical identity: Unknown</b><span>AI-generated prioritization. Not a chemical diagnosis. Laboratory and field verification are required.</span></div></div><div className="doc-source"><Database/> Sources: citizen reports · GPS/timestamps · mock factory registry · mock flood layer · local incident history</div></div><div className="submit-bar"><div><Badge tone="blue">PROTOTYPE / MOCK INTEGRATION</Badge><p>AI intelligence layer → existing reporting infrastructure</p></div><button className="primary big" onClick={()=>go('tracking')}><Send/> Submit incident <ArrowRight/></button></div></div>}

function Tracking({go}:{go:(s:Screen)=>void}){const [submitted,setSubmitted]=useState(false); useState(()=>{reportingIntegration.createIssue({incident:'PB-024'}).then(()=>setSubmitted(true))}); const timeline=[['Report received',true],['AI triage completed',true],['Incident cluster detected',true],['Submitted to responsible system',submitted],['Awaiting officer verification',false]]; return <div className="page success-page"><div className={`success-icon ${submitted?'done':''}`}>{submitted?<Check/>:<Send/>}</div><Badge tone="blue">PROTOTYPE / MOCK INTEGRATION</Badge><h1>{submitted?'Incident submitted successfully':'Submitting structured incident…'}</h1><p>{submitted?'The mock adapter accepted the officer-ready report. No government system was contacted.':'Sending through the simulated reporting-system adapter.'}</p>{submitted&&<div className="tracking-id"><span>TRACKING ID</span><b>PB-024</b><small>Created 02 Oct 2026 · 11:41 ICT</small></div>}<div className="timeline">{timeline.map(([label,active],i)=><div key={String(label)} className={active?'active':''}><span>{active?<Check/>:i===4?<Clock3/>:<CircleDot/>}</span><b>{label}</b>{i<timeline.length-1&&<i/>}</div>)}</div><SafetyNote/><div className="success-actions"><button className="primary" onClick={()=>go('detail')}>Track incident <ChevronRight/></button><button className="secondary" onClick={()=>go('home')}>Return home</button></div></div>}

function How({go}:{go:(s:Screen)=>void}){const flow=[[FileText,'Citizen report','Image + Thai/English text'],[Bot,'Multimodal understanding','Extract observations—not chemicals'],[Database,'Context retrieval','Nearby reports · location · industry · flood · history'],[Network,'Incident clustering','Spatial 40% · temporal 30% · semantic 30%'],[Radar,'Risk / priority engine','Transparent demo weights'],[ShieldCheck,'Human verification','Officers + laboratory testing'],[Send,'Existing infrastructure','Replaceable mock adapter']]; return <div className="page how-page"><div className="page-title"><button className="icon-btn" onClick={()=>go('home')}><X/></button><div><span>SYSTEM ARCHITECTURE</span><h1>How the AI Concierge works</h1></div></div><p className="how-lead">Not “user → LLM → answer.” The prototype combines structured understanding, retrieval, clustering, transparent scoring, and tool integration.</p><div className="architecture">{flow.map(([Icon,title,sub]:any,i)=><Fragment key={title}><div className="arch-card"><Icon/><span><b>{title}</b><small>{sub}</small></span></div>{i<flow.length-1&&<ArrowRight className="arch-arrow"/>}</Fragment>)}</div><div className="capabilities">{[['REMEMBER','Historical incidents and recurring risk areas'],['UNDERSTAND','Turn messy reports into structured observations'],['CONNECT','Join citizen signals with location context'],['RETRIEVE','Fetch evidence, guidance, and agencies'],['REASON','Cluster incidents and prioritize urgency'],['ACT','Prepare a report for existing systems']].map(x=><div key={x[0]}><span>{x[0]}</span><p>{x[1]}</p></div>)}</div><div className="principles"><section><h2><ShieldCheck/> Responsible by design</h2><ul><li>Does not identify a chemical from an image</li><li>Does not replace officers or laboratory testing</li><li>Shows confidence, sources, and contributing factors</li><li>High-risk cases always require human verification</li></ul></section><section><h2><Layers3/> Integration-ready</h2><p>A typed adapter isolates this intelligence layer from downstream systems. The demo mocks three future capabilities:</p><div className="code-lines"><code>getNearbyIssues()</code><code>createIssue()</code><code>receiveIssueUpdate()</code></div></section></div><button className="primary" onClick={()=>go('report')}>Try the demo <ArrowRight/></button></div>}

export function App(){const [screen,setScreen]=useState<Screen>('home'); const view=useMemo(()=>({home:<Home go={setScreen}/>,report:<Report go={setScreen}/>,analysis:<Analysis go={setScreen}/>,cluster:<Cluster go={setScreen}/>,detail:<Detail go={setScreen}/>,structured:<Structured go={setScreen}/>,tracking:<Tracking go={setScreen}/>,how:<How go={setScreen}/>})[screen],[screen]); return <Shell screen={screen} setScreen={setScreen}>{view}</Shell>}
